services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "7878:7878"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "81:3000"
