services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "80:7878"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "81:8000"
