[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 3000


[[proxy]]
backend = "http://localhost:7878/api/echo"

[[proxy]]
backend = "http://localhost:7878/api/sample"

[[proxy]]
backend = "http://localhost:7878/api/compile"
