[package]
name = "conqiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.3"
melior = "0.17.0"
rand = "0.8.5"
tempfile = "3.10.1"
